services:
  www:
    image: 739471740344.dkr.ecr.eu-west-2.amazonaws.com/huddle_www
    depends_on:
      - backend
    ports:
      - 80:80
      - 443:443

  backend:
    image: 739471740344.dkr.ecr.eu-west-2.amazonaws.com/huddle_back
    depends_on:
       - database
    environment:
      PORT: 3000
      NODE_ENV: '${HUDDLE_NODE_ENV}'
      HUDDLE_OPENAI_API_KEY: '${HUDDLE_OPENAI_API_KEY}'
      HUDDLE_LOGIN_TOKEN_SECRET: '${HUDDLE_LOGIN_TOKEN_SECRET}'
      HUDDLE_MESSAGE_KEY: '${HUDDLE_MESSAGE_KEY}'
      HUDDLE_WAITLIST_SIGNUP_WEBHOOK: '${HUDDLE_WAITLIST_SIGNUP_WEBHOOK}'
      HUDDLE_POSTGRES_PASSWORD: '${HUDDLE_POSTGRES_PASSWORD}'

  database:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_PASSWORD: '${HUDDLE_POSTGRES_PASSWORD}'
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
