services:
  backend:
    image: huddle
    working_dir: /huddle
    command: sh -c 'cd huddle && node main.js'
    depends_on:
       - database

  database:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
