services:
  backend:
    image: huddle
    working_dir: /huddle/back
    command: sh -c 'node main.js'
    depends_on:
       - database
    environment:
      PORT: '${HUDDLE_PORT}'
      NODE_ENV: '${HUDDLE_NODE_ENV}'
      HUDDLE_OPENAI_API_KEY: '${HUDDLE_OPENAI_API_KEY}'
      HUDDLE_LOGIN_TOKEN_SECRET: '${HUDDLE_LOGIN_TOKEN_SECRET}'
      HUDDLE_MESSAGE_KEY: '${HUDDLE_MESSAGE_KEY}'
      HUDDLE_WAITLIST_SIGNUP_WEBHOOK: '${HUDDLE_WAITLIST_SIGNUP_WEBHOOK}'
    ports:
      - '${HUDDLE_PORT}:${HUDDLE_PORT}'

  database:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_PASSWORD: '${HUDDLE_POSTGRES_PASSWORD}'
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
